### ISSUE TITLE
Explore :local scoped css

### ISSUE THREAD

**Issue by oliger** [hull-ships/hull-login#10]
https://github.com/webpack/css-loader

**Comment by citelao** [comment]
:+1:

**Comment by oliger** [comment]
https://github.com/bloodyowl/react-styled

**Comment by oliger** [comment]
https://github.com/MicheleBertoli/css-in-js

**Comment by citelao** [comment]
This might make caching weird, though.

**Comment by oliger** [comment]
@citelao Not sure to get what you mean. I'm playing with it in the poll ship and it works well.
