### ISSUE TITLE
Auto-closing modal is not cancelable

### ISSUE THREAD

**Issue by citelao** [hull-ships/hull-login#13]
The post-signup auto-close should be disabled if

- the user interacts with the modal
- the user must complete more information

Or we can just disable this feature entirely— it's a little confusing.

**Comment by oliger** [comment]
> the user interacts with the modal

I think this is already the case. see: https://github.com/hull-ships/hull-login/blob/master/src/lib/engine.js#L217

**Comment by citelao** [comment]
Mouse focus, typing, clicking on the modal, etc. don't cancel the auto-close I don't think

**Comment by oliger** [comment]
I think you are right. Do we want to handle this?

**Comment by citelao** [comment]
We might just want to remove it; it's confusing behavior.

**Comment by oliger** [comment]
Not sure to get what you want to remove :/

**Comment by citelao** [comment]
It was a bug. It was supposed to only happen on the `thanks` page but it was happening elsewhere.

Not a problem anymore.
