### ISSUE TITLE
Modal opens by itself

### ISSUE THREAD

**Issue by unity** [hull-ships/hull-login#16]
http://embedded-ship.hullbeta.io/?platformId=558a7abcf71ca07c50001130&orgUrl=https%3A%2F%2Fsuper.hullapp.io
Modal opens automatically. Happened to me on main website while testing.
Should never happen I guess

**Comment by oliger** [comment]
That is a feature, I do not like it but shopify shop owners want it. Can be disabled with `show_sign_up_section_after`.
