### ISSUE TITLE
Experience is confusing when an error happened when the login strategy is `redirect`

### ISSUE THREAD

**Issue by oliger** [hull-ships/hull-login#20]
Experience is confusing when an error happened when the login strategy is `redirect`. There is no error message, and the login dialog is closed...

**Comment by unity** [comment]
I think this should be handled by hull.js

**Comment by oliger** [comment]
@unity Open a new window that trigger success/failure in the parent one?

**Comment by citelao** [comment]
Does login strategy `redirect` not call `logIn()`? https://github.com/hull-ships/hull-login/blob/master/src/lib/engine.js#L245-L259

**Comment by unity** [comment]
No I was thinking
- submit via Ajax ("test login")
- get response
- if valid, redo login, via redirect this time. 
- else, show error. 

This way we stay in the page and not pollute with popups, and if account is valid then we login again via redirect ("sticky" login)

**Comment by unity** [comment]
If we had a way to know if Ajax login was sticky, we could have the "post" used only as a fallback to the "regular" login

**Comment by oliger** [comment]
How do you handle success with this solution? For example on the `hull-login` ship, we display a thanks or a complete profile screen.

**Comment by oliger** [comment]
> If we had a way to know if Ajax login was sticky

You want to know if the cookie has been set?

**Comment by unity** [comment]
Didn't think about this one :) 
Was mainly focused on failure scenario
Can we detect success after redirect ?

**Comment by oliger** [comment]
> Can we detect success after redirect ?

We can add an hash in the URL, but reconstructing the ship state will be difficult. That is why I was proposing to open a window triggers success/failure in the parent one.

**Comment by unity** [comment]
Maybe the "thanks" screen should depend on persisted data such as total session count (I was using stats.sign_in_count) to detect wether we are creating or logging in. Quite robust if know count is correct. 

As for the pop up solution : it would open an annoying window everytime you post a bad login. Seems bad ux. 

What we could do is combine our two approaches: 

- Perform Ajax login
- if invalid, display error
- if valid, login again using self-closing popup

What we need to validate:
- 3rd party cookie restriction is lifted when just popping up a window, and not necessarily clicking it. (Not sure about this)
- can we actually detect cookie set when domain isn't whitelisted: it might set the cookie and just delete it when window closes - you wouldn't be able to know then.

**Comment by unity** [comment]
This is some hardcore way to workaround. Maybe some ideas to lift: http://measurablewins.gregjxn.com/2014/02/safari-setting-third-party-iframe.html

**Comment by oliger** [comment]
> Maybe the "thanks" screen should depend on persisted data such as total session count (I was using stats.sign_in_count) to detect wether we are creating or logging in. Quite robust if know count is correct.

Yes, maybe my example was not good... For the `hull-login` ship reconstructing the state is not that hard... My point was that it is easy to loose some data when refreshing the page.

> As for the pop up solution : it would open an annoying window everytime you post a bad login. Seems bad ux.

I agree.

> What we could do is combine our two approaches:

Yep.

**Comment by oliger** [comment]
> Does login strategy redirect not call logIn()? https://github.com/hull-ships/hull-login/blob/master/src/lib/engine.js#L245-L259

@citelao `logIn()` calls `Hull.login()`. the redirect is made by `Hull.login()`. Then once the page is redirect state.
