### ISSUE TITLE
Allow user to upload a profile picture

### ISSUE THREAD

**Issue by oliger** [hull-ships/hull-login#3]
In the "edit" section, the user should be able to upload a new profile picture.

The user can ether drop an image file on his current profile picture or click on his current picture to pick an image file in the explorer.

See [the component that does the same thing in our dashboard](https://github.com/hull/hull-admin/blob/develop/src/app/components/ui/image-input.jsx).

**Comment by unity** [comment]
Will probably need a bit more work and thought than the dashboard : image
size limits have to be put in place, and profile pictures would need to be
resized/cropped somehow. A good way to reuse existing stuff might be to
start from our image Api and improve it ?

If we use the component from the dashboard we'd be happy to see it enhanced
to support cropping. There's a jquery plugin for fileAPI that handles
cropping. Could be also a good basis for react implementation ?. (
http://rubaxa.github.io/jquery.fileapi/)

**Comment by unity** [comment]
Also, maybe this can be useful : http://mosch.github.io/react-avatar-editor/

**Comment by citelao** [comment]
#22 fixes
