### ISSUE TITLE
Add enter/leave animation on overlay 

### ISSUE THREAD

**Issue by oliger** [hull-ships/hull-login#4]
https://github.com/hull-ships/hull-login/blob/master/src/components/overlay/index.jsx#L35-L41

**Comment by citelao** [comment]
How do you like this animation:

http://bouncejs.com/#{s:[{T:"t",e:"b",d:500,D:0,f:{x:0,y:100},t:{x:0,y:0},s:3,b:4},{T:"c",e:"b",d:500,D:0,f:{x:1,y:0.5},t:{x:1,y:1},s:3,b:4},{T:"c",e:"b",d:100,D:0,f:{x:0.5,y:1},t:{x:0.5,y:1},s:3,b:4},{T:"c",e:"b",d:500,D:100,f:{x:1,y:1},t:{x:2,y:1},s:3,b:4}]}

**Comment by oliger** [comment]
It can be cool. Try it :)

**Comment by citelao** [comment]
Fixed in #8
