### ISSUE TITLE
Improve Form

### ISSUE THREAD

**Issue by oliger** [hull-ships/hull-login#5]
- [ ] add `radio`
- [ ] add `checkbox`
- [ ] add `optgroup`
- [ ] add the option to render `<select multiple=false>` as multiple radios
- [ ] add the option to render `<select multiple=true>` as multiple checkboxes
- [ ] add `lists`
- [ ] support `date`/`datetime`/`time` in older browser.

**Comment by unity** [comment]
Was thinking it would be useful to extract the form as a standalone repo so we could use it in other ships without having features diverge. Quiz ship needs a form component too. In a more general question. How do we package login flow so it can be reused in quiz and comments ships ?

**Comment by citelao** [comment]
Hull-login currently uses [tcomb-forms](http://gcanti.github.io/tcomb-form/). I can just create a theme for that.

**Comment by oliger** [comment]
@citelao https://github.com/hull-ships/hull-login/blob/master/src/components/form/templates/index.js

**Comment by citelao** [comment]
If I finish the theme there should I just port it into quizzes, too?

**Comment by oliger** [comment]
Finish it inside hull-login first. Then extract it and use it in hull-quiz :)
